### Handling Imbalanced Dataset with Machine Learning

In [4]:
import pandas as pd
df=pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.shape

(284807, 31)

In [5]:
df.isnull().count()

Time      284807
V1        284807
V2        284807
V3        284807
V4        284807
V5        284807
V6        284807
V7        284807
V8        284807
V9        284807
V10       284807
V11       284807
V12       284807
V13       284807
V14       284807
V15       284807
V16       284807
V17       284807
V18       284807
V19       284807
V20       284807
V21       284807
V22       284807
V23       284807
V24       284807
V25       284807
V26       284807
V27       284807
V28       284807
Amount    284807
Class     284807
dtype: int64

In [6]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
### Independent and Dependent Features
X=df.drop('Class',axis=1)
y=df.Class

### Cross validation like KFold and hyper parameter Tuning

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics  import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [11]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

NameError: name 'X' is not defined

In [13]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.83211491        nan 0.8378966         nan 0.82901721
        nan 0.83571801        nan 0.83557658]
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [15]:
y_preds=clf.predict(X_test)
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))

[[85241    46]
 [   62    94]]
0.998735999438222
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.67      0.60      0.64       156

    accuracy                           1.00     85443
   macro avg       0.84      0.80      0.82     85443
weighted avg       1.00      1.00      1.00     85443



In [16]:
from sklearn.ensemble import RandomForestClassifier
clfr=RandomForestClassifier()
clfr.fit(X_train,y_train)

RandomForestClassifier()

In [18]:
y_preds=clfr.predict(X_test)
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))

[[85278     9]
 [   34   122]]
0.9994967405170698
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.93      0.78      0.85       156

    accuracy                           1.00     85443
   macro avg       0.97      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [19]:
class_weight=dict({0:1,1:100})

In [20]:
from sklearn.ensemble import RandomForestClassifier
clfr=RandomForestClassifier(class_weight=class_weight)
clfr.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [21]:
y_preds=clfr.predict(X_test)
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))

[[85280     7]
 [   37   119]]
0.9994850368081645
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.94      0.76      0.84       156

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



### Under Sampling

In [40]:
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)
print(Counter(y_train))
print(Counter(y_train_ns))

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


Counter({0: 199028, 1: 336})
Counter({0: 420, 1: 336})


In [41]:
from sklearn.ensemble import RandomForestClassifier
clfr=RandomForestClassifier()
clfr.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [42]:
y_preds=clfr.predict(X_test)
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))

[[61057 24230]
 [    9   147]]
0.7163137998431703
              precision    recall  f1-score   support

           0       1.00      0.72      0.83     85287
           1       0.01      0.94      0.01       156

    accuracy                           0.72     85443
   macro avg       0.50      0.83      0.42     85443
weighted avg       1.00      0.72      0.83     85443



### OverSampling

In [43]:
from imblearn.over_sampling import RandomOverSampler

In [45]:
os=RandomOverSampler(0.5)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print(Counter(y_train))
print(Counter(y_train_ns))

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


Counter({0: 199028, 1: 336})
Counter({0: 199028, 1: 99514})


In [46]:
from sklearn.ensemble import RandomForestClassifier
clfr=RandomForestClassifier()
clfr.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [47]:
y_preds=clfr.predict(X_test)
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))

[[85278     9]
 [   32   124]]
0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.93      0.79      0.86       156

    accuracy                           1.00     85443
   macro avg       0.97      0.90      0.93     85443
weighted avg       1.00      1.00      1.00     85443



### SMOTETomek

In [1]:
from imblearn.combine import SMOTETomek

In [ ]:
os=SMOTETomek(0.5)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print(Counter(y_train))
print(Counter(y_train_ns))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clfr=RandomForestClassifier()
clfr.fit(X_train_ns,y_train_ns)

In [ ]:
y_preds=clfr.predict(X_test)
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))